name: Run Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Create test-results directory
        run: mkdir -p test-results

      - name: Run Firestore Rules Tests with Emulator
        run: |
          npm install -g firebase-tools
          firebase emulators:exec --only firestore "node firestore-test.js" | tee test-results/firestore-results.log

      - name: Run Jest Tests
        run: npm test | tee test-results/jest-results.xml

      - name: Merge all test results into one file
        run: cat test-results/firestore-results.log test-results/jest-results.xml > test-results/full-test-report.log

      - name: Upload Test Results (Always)
        uses: actions/upload-artifact@v4
        with:
          name: full-test-results
          path: test-results/
