name: Run Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Run Firestore Rules Tests with Emulator
        run: |
          npm install -g firebase-tools
          firebase emulators:exec --only firestore "node firestore-test.js"

      - name: Run Jest Tests
        run: npm test

      - name: Upload Jest Test Results (if failed)
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: jest-test-results
          path: test-results/
